### ISSUE TITLE
Obscure error with prompt_toolkit on entering git commands

### ISSUE THREAD

**Issue by mdraw** [scopatz/xonsh#380]
I am using the current git version of xonsh 201484a with prompt_toolkit on Arch Linux.
On entering `git clone '` or `git clone #` (not executing, just entering those characters), xonsh crashes with the following error:

    Exception in thread Thread-184:
    Traceback (most recent call last):      
      File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()                          
      File "/usr/lib/python3.4/threading.py", line 868, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 510, in run
        CompleteEvent(text_inserted=True))) 
      File "/usr/lib/python3.4/site-packages/xonsh/prompt_toolkit_completer.py", line 30, in get_completions
    self.ctx)
      File "/usr/lib/python3.4/site-packages/xonsh/completer.py", line 134, in complete
    for s in self.bash_complete(prefix, line, begidx, endidx):
      File "/usr/lib/python3.4/site-packages/xonsh/completer.py", line 265, in bash_complete
    stderr=subprocess.PIPE)
      File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
    subprocess.CalledProcessError: Command '['bash']' returned non-zero exit status 1

I don't know if this is a bug in xonsh or in prompt_toolkit and don't really understand what is happening there, so I am just reporting it here, hoping that someone can explain/fix this.
Strangely, I could only reproduce this bug with git subcommands, while other commands worked fine with these characters. So I guess it could also be a specific problem with git autocompletion.

**Comment by scopatz** [comment]
Thanks for reporting @mdraw. Do you hit TAB after entering the single quote or hash symbol?

**Comment by scopatz** [comment]
This is almost certainly a git completion thing.  Ahhh, also, if you are on prompt-toolkit, pt may be running completion for you automatically.  This probably needs to be more robust.

**Comment by mdraw** [comment]
I did not hit TAB after entering the mentioned commands. The errors occur immediately when typing the single quotes and hashes.
Another detail: I also noticed that the error does not occur if you write something before the `#` sign, like e.g. `git clone git://anongit.kde.org/yakuake.git#branch=frameworks` works fine.
Can you reproduce this?

**Comment by scopatz** [comment]
Sorry about the delay here. I am not able to reproduce this because I am not using prompt-toolkit (yet). Maybe @jonathanslenders or someone else can reproduce this...

**Comment by melund** [comment]
I also thought it was related to this https://github.com/scopatz/xonsh/issues/364 , and the fact that prompt_toolkit runs completion automatically. However, I have tried to reproduce this on Windows without any luck. I running with the the newest prompt_toolkit (from github) and xonsh.

**Comment by scopatz** [comment]
Thanks for trying @melund!

**Comment by scopatz** [comment]
Maybe this is fixed on some of the newer versions of promt-toolkit / xonsh.

**Comment by mdraw** [comment]
Using the current xonsh 8a55f2b and prompt_toolkit 0.52, the same error still occurs on my machine.

**Comment by scopatz** [comment]
Hmm annoying...

**Comment by gforsyth** [comment]
Hey @mdraw -- I'm also on Arch but can't seem to reproduce this.  Is it still an issue for you?

**Comment by mdraw** [comment]
Indeed, it seems to be fixed now. Thanks for noticing, @gforsyth!
Closing.
