### ISSUE TITLE
xonsh goes crazy when calling itself

### ISSUE THREAD

**Issue by icarito** [scopatz/xonsh#46]
icarito@aiki ~ $ xonsh --help
<function default_prompt at 0xb6cefb6c> # wtf?
.......................................
.......................................
.......................................exit
.....................................................................................................................

**Comment by scopatz** [comment]
This does not happen on the current master for me:

```console
scopatz@athenaie ~ $ xonsh --help
usage: xonsh [-h] [-c COMMAND]

xonsh

optional arguments:
  -h, --help  show this help message and exit
  -c COMMAND  Run a single command and exit

```

**Comment by icarito** [comment]
I don't know why.

I just installed with pip and haven't logged out yet.

I'm running up to date manjaro (arch based) OS.

Let me know if you need anything more to debug.

btw nice project!

**Comment by scopatz** [comment]
OK this is probably fixed in master then.  I am going to do a new pip release later tonight to deploy the fix.  Thanks!

**Comment by icarito** [comment]
Just logged out and back in, problem persists.

Reset, clear, or any other command, don't work at all once it goes into
"dots" mode

**Comment by scopatz** [comment]
Did you install from master?

**Comment by icarito** [comment]
Finally I did:
sudo pip install git+https://github.com/scopatz/xonsh --upgrade

This installed master for me and now it's fixed.

I just learned that pip incantation, I'm really happy about it :-)

**Comment by scopatz** [comment]
Haha nice.  I am glad it is fixed.  Thanks a ton for reporting @icarito.

**Comment by scopatz** [comment]
closing this issue. please reopen if you feel it hasn't been addressed.
