### ISSUE TITLE
Running python's quit() causes unclean exit with file write error.

### ISSUE THREAD

**Issue by Samathy** [scopatz/xonsh#59]
Using the python function quit() from the xonsh shell results in a spew of traceback finally resulting in a file writing error.

Possibly redirect python's quit() to xonsh's own exit method as the latter seems to exit cleanly.

![xonsh_error](https://cloud.githubusercontent.com/assets/6306834/6665601/4419f40a-cbd3-11e4-89b9-ffc9fdc66d46.png)

**Comment by scopatz** [comment]
Nice catch @Samathy.  6f5da3d should fix the issue. Please let me know how it goes.

**Comment by Samathy** [comment]
Sorry for the late reply:

It seems that didnt fix the issue. 

![xonsh_quit2](https://cloud.githubusercontent.com/assets/6306834/6708939/d1f1a314-cd6c-11e4-99a7-f6af3e7a51f2.png)

**Comment by scopatz** [comment]
Try it without the parentheses.

**Comment by Samathy** [comment]
Yep, that works fine.

**Comment by scopatz** [comment]
Great.  Feel free to close if you think that this has been addressed!
